### ISSUE TITLE
Put in KX 12 Froala Editor instructions for legacy users

### ISSUE THREAD

**Issue by KenticoDevTrev** [Kentico/xperience-component-samples#146]
The Froala Editor for KX 12 is no longer found, with it's instructions.  I have it forked on mine, perhaps put that folder back for those still on 12?

Original Location:
https://github.com/Kentico/xperience-component-samples/tree/master/Kentico.InlineEditor.RichText
 
My Fork:
https://github.com/KenticoDevTrev/ems-mvc-components?organization=KenticoDevTrev&organization=KenticoDevTrev
 
Mainly need this reference to the nuget and instructions:
 
Kentico.EMS12.MvcComponents.Widget.RichText

**Comment by petrinecp** [comment]
Hi @KenticoDevTrev you can find the repository in previous by selecting a specific version tag.
![image](https://user-images.githubusercontent.com/5637849/108827320-c344b880-75c5-11eb-8f6f-911c076e6bb4.png)
