### ISSUE TITLE
How to install those component to an Kentico xperience

### ISSUE THREAD

**Issue by nhokgames1** [Kentico/xperience-component-samples#147]
Hi guys, I new to Kentico.
My question is how I can install it on my local?
For example, I trying to install it on my DancingGoat Kentico but I unable to understand how to do that.
Thanks

**Comment by petrinecp** [comment]
Hi @nhokgames1 which version of Kentico are you using? If you're on 13 (Kentico Xperience) and you're intrested in the Rich Text widget, you no longer need to install it separately as this widget has been baked into the product in version 13. Or are you interested in a different component from this repository?

**Comment by nhokgames1** [comment]
Hi @petrinecp 
Thanks so much for your response.
I would like to install 2 components from the repo which is:
Object selector form component
Video widget
Thanks

**Comment by petrinecp** [comment]
Hi @nhokgames1 you can find the installation steps in each component's README.md file. At the moment only the Video widget is recommended for installation and has the steps listed there, however the same process works for the object selector too.

**Comment by nhokgames1** [comment]
![image](https://user-images.githubusercontent.com/16149105/109793280-072f6180-7c47-11eb-868c-7e5e55414b45.png)
I copied the Kentico.Widget.Video.Views.dll and Kentico.Widget.Video.dll to C:\inetpub\wwwroot\Kentico13\CMS\bin and I got this error, can you help me with it?

**Comment by petrinecp** [comment]
Hi @nhokgames1, you need to copy these dll in your MVC site's project, not the administration. If your project is MVC Core, you also need to include the dlls as assembly references into your project.

**Comment by nhokgames1** [comment]
Thanks so much for your reply.
I did as per your instruction, but I got another issue as the picture below
![image](https://user-images.githubusercontent.com/16149105/109910833-971eeb00-7cdb-11eb-806f-6cefefa33920.png)

**Comment by petrinecp** [comment]
Hi @nhokgames1 after taking a better look on this repository (it's been a while), I must say that the components in its current state are only meant for .NET Core projects on Xperience 13.

**Comment by petrinecp** [comment]
@nhokgames1 However you can switch to v1.3.0-richtext tag when the repository was targeting Kentico 12 and you can copy the source files of the widget into your Xperience 13 MVC project and it will work (tested this now). You need to copy the classes, views, and you have to build the javacsript/css and copy them over.
![image](https://user-images.githubusercontent.com/5637849/109949813-1e6c5e80-7cdc-11eb-8763-e9f51001964c.png)

**Comment by nhokgames1** [comment]
Hi @petrinecp,
 I must say I very much appreciate your support.
Can you help me to clarify that what file I need to copy, for example, the Kentico Video widget perhaps?
Thanks

**Comment by petrinecp** [comment]
Hi @nhokgames1, I'm sorry for the delayed response, but here are the steps needed, demonstrated on the Dancing Goat MVC sample site:

1. Download the repository in state tagged v1.3.0-richtext
2. Unzip it and navigate to the repository folder in powershell and type `npm install && npm run build` (you need nodejs installed for this)
3. Copy `Kentico.Widget.Video\Controllers\KenticoVideoWidgetController.cs` to `DancingGoatMvc\Controllers\Widgets`
4. Copy `VideoHelper.cs` and `VideoKindEnum.cs` from `Kentico.Widget.Video\Helpers` to `DancingGoatMvc\Helpers`
5. Copy `VideoModel.cs` and `VideoWidgetProperties.cs` from `Kentico.Widget.Video\Models\Widgets` to `DancingGoatMvc\Models\Widgets\VideoWidget` (create the `VideoWidget` folder)
6. Copy `InlineEditors` and `Widgets` folders from `Kentico.Widget.Video\Content` to `DancingGoatMvc\Content`
7. Copy `Kentico.Widget.Video\App_Data\Global\Resources\Kentico.Widget.Video.resx` to `DancingGoatMvc\App_Data\Global\Resources`
8. Copy `Kentico` folder in `Kentico.Widget.Video.Views\Views\Shared` to `DancingGoatMvc\Views\Shared`
9. Now open the `DancingGoatMvc.sln` and include all the copied files in the project
10. Open `KenticoVideoWidgetController` class and add a private field and constructor
`private readonly IComponentPropertiesRetriever componentPropertiesRetriever;`
` `
`public KenticoVideoWidgetController(IComponentPropertiesRetriever componentPropertiesRetriever)`
`{`
`    this.componentPropertiesRetriever = componentPropertiesRetriever;`
`}`
12. Replace the deprecated `GetProperties()` call with `componentPropertiesRetriever.Retrieve<VideoWidgetProperties>()`
13. Build the project
14. The Video Widget should now be available and working on the Home page
